version: "3.4"

services:
  golang:
    image: golang:stretch
    depends_on:
      - kafka
      - zookeeper
      - mongo
    environment:
      KAFKA_EMULATOR_BOOTSTRAP_SERVER: localhost:9092
    volumes:
      - .:/kit
    working_dir: /kit

  kafka:
    image: confluentinc/cp-kafka:5.0.0
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
    ports:
      - "9092:9092"
  
  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - 2181:2181

  mongo:
    image: mongo:3.4.5
    ports:
      - 27017:27017